# Generated by Django 5.0.6 on 2024-06-28 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0001_initial"),
        ("core", "0007_pontoturistico_descricao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Avalicao",
            new_name="Avaliacao",
        ),
    ]
