# Generated by Django 5.0.6 on 2024-06-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pontoturistico",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
    ]
