# Generated by Django 5.0.6 on 2024-06-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pontoturistico_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="descricao",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
